// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bT8f6PJZnAel0SYX9FjpaPwExdyMGHU',
    appId: '1:221162694017:web:bdefd42280bc3d3a74b480',
    messagingSenderId: '221162694017',
    projectId: 'tour-trove',
    authDomain: 'tour-trove.firebaseapp.com',
    storageBucket: 'tour-trove.appspot.com',
    measurementId: 'G-11GCSYDGVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa4OGbNUn1spw0xgH0mNnBAero75iUPiI',
    appId: '1:221162694017:android:0abacd7593086b2774b480',
    messagingSenderId: '221162694017',
    projectId: 'tour-trove',
    storageBucket: 'tour-trove.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnteF-wraftS5yYxRqL3fWVzzmh5B7cwE',
    appId: '1:221162694017:ios:92028cdf945c64c674b480',
    messagingSenderId: '221162694017',
    projectId: 'tour-trove',
    storageBucket: 'tour-trove.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnteF-wraftS5yYxRqL3fWVzzmh5B7cwE',
    appId: '1:221162694017:ios:57a146d7713d8df374b480',
    messagingSenderId: '221162694017',
    projectId: 'tour-trove',
    storageBucket: 'tour-trove.appspot.com',
    iosBundleId: 'com.example.dalel.RunnerTests',
  );
}
